spring:
  cloud:
    stream:
      bindings:
        output:
          destination: mysql-migration
      kafka:
        binder:
          configuration:
            key:
              serializer: org.apache.kafka.common.serialization.StringSerializer